### ISSUE TITLE
编译libsrtp.lib报错

### ISSUE THREAD

**Issue by wenfengtou** [Harley-Huanglei/webrtc_vs#1]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	MSB3073	命令“copy /Y D:\work\webrtc_vs\project\Debug\libsrtp.lib ..\x86-windows-cl14\lib\libsrtp-g.lib
:VCEnd”已退出，代码为 1。	libsrtp	D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	155

**Comment by wenfengtou** [comment]
copy /Y $(targetpath) ..\..\opus\x86-windows-cl14\lib\libsrtp-g.lib

**Comment by Harley-Huanglei** [comment]
感谢提醒，已经解决上传。仓库的代码比较老，如果有资源，建议去更新google的repository去下载代码进行编译调试

**Comment by wenfengtou** [comment]
Up主您是用什么方法把webrtc的源码编译成一个个vs使用的lib库的

**Comment by Harley-Huanglei** [comment]
https://github.com/hujianhua888/webrtc_vs2015  ，原始git仓库在这，我在这个仓库基础上改动出出来的。关于如果从源码搭建工程，需要有vpn支持，类似方案参考  https://blog.csdn.net/icsecurity/article/details/109226458
